### ISSUE TITLE
curl_init() doesn't work properly according to requirement

### ISSUE THREAD

**Issue by rohitnehra** [curl/curl-up#1]
<?php
function SendMessage($mobile, $text)
{
$message ="Hi ".$row['name']." ".$_GET['TxtMsg'].",";
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://www.mysmsapp.in/api/push.json?apikey=xxxxxxx&sender=xxxxxx&mobileno=".$mobile."&text=".$text);
curl_exec($ch);
curl_close($ch);
}
 ?>

I have this function for sending messages. It shows internal server error whenever I run it more than 100 times. I tried multi function also but that also didn't work. Please tell me a solution to execute it in regular interval of time. So that my api have no issues in sending messages

**Comment by xquery** [comment]
this repo is for the curl conference ... you should file this issue (with a bit more detail and code examples) here:

https://github.com/curl/curl/issues
